name: amogus
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    # Elements Icons
    - assets/icons/Elements/
    - assets/icons/
    # Types
    - assets/icons/WeapType/
    - assets/icons/AmmoType/
    # Weapon Sharpness
    - assets/icons/WeapSharp/
    # Weapon Ranks
    - assets/icons/WeapRank/Long_Sword/
    - assets/icons/WeapRank/Sword_&_Shield/
    - assets/icons/WeapRank/Charge_Blade/
    - assets/icons/WeapRank/Dual_Blades/
    - assets/icons/WeapRank/Gunlance/
    - assets/icons/WeapRank/Lance/
    - assets/icons/WeapRank/Hunting_Horn/
    - assets/icons/WeapRank/Switch_Axe/
    # Armor Sets
    - assets/ArmorSets/
    - assets/ArmorSets/LR/
    - assets/ArmorSets/HR/
    - assets/ArmorSets/LR/Blademaster/
    - assets/ArmorSets/HR/Blademaster/
    - assets/ArmorSets/LR/Gunner/
    - assets/ArmorSets/HR/Gunner/
    # Armor Icons
    - assets/icons/ArmorType/
    # Categories Icons
    - assets/icons/Categories/
    # Gifs
    - assets/gifs/
    # Misc
    - assets/icons/Misc_ui/

  fonts:
    - family: FiraCode
      fonts:
        - asset: fonts/FiraCode-Bold.ttf
        - asset: fonts/FiraCode-Light.ttf
        - asset: fonts/FiraCode-Medium.ttf
        - asset: fonts/FiraCode-Regular.ttf
        - asset: fonts/FiraCode-Retina.ttf
        - asset: fonts/FiraCode-SemiBold.ttf
  
