// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgG10BWgrJoJCIssdyR1xz2qjFGSBLY08',
    appId: '1:1034473494590:web:829b1ca95f46027176996f',
    messagingSenderId: '1034473494590',
    projectId: 'amogusmhdb',
    authDomain: 'amogusmhdb.firebaseapp.com',
    storageBucket: 'amogusmhdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfAjn_G6piBUj8h8Saztkv4yD2nDwK1YA',
    appId: '1:1034473494590:android:34b2fb27910af5f976996f',
    messagingSenderId: '1034473494590',
    projectId: 'amogusmhdb',
    storageBucket: 'amogusmhdb.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxKh_d_JWQtYOuny5O8lAaBQ0iZls29pk',
    appId: '1:1034473494590:ios:9e3b36913168311876996f',
    messagingSenderId: '1034473494590',
    projectId: 'amogusmhdb',
    storageBucket: 'amogusmhdb.appspot.com',
    iosBundleId: 'com.example.amogus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgG10BWgrJoJCIssdyR1xz2qjFGSBLY08',
    appId: '1:1034473494590:web:f7748ccca06ccb8976996f',
    messagingSenderId: '1034473494590',
    projectId: 'amogusmhdb',
    authDomain: 'amogusmhdb.firebaseapp.com',
    storageBucket: 'amogusmhdb.appspot.com',
  );
}
